version: '3'
services:
  server:
    build: .
    container_name: server
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    env_file:
      - ./backend/Server/.env
    restart: always
    command: node /app/backend/Server/server.js 

  bot:
    build: .
    container_name: bot
    env_file:
      - ./backend/Bot/.env
    command: node /app/backend/Bot/bot.js 
    depends_on:
      - server
    restart: always

  datafrontend:
    image: nginx:latest
    container_name: datafrontend
    ports:
      - "4000:80"
    volumes:
      - ./backend/DataFrontend:/usr/share/nginx/html
    restart: always
    
  frontend:
    image: nginx:latest
    container_name: frontend
    ports:
      - "5000:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    restart: always
