services:
  server:
    build: .
    container_name: server
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    env_file:
      - ./Server/.env
    restart: always
    command: node /app/Server/server.js # Команда для запуска сервера

  bot:
    build: .
    container_name: bot
    env_file:
      - ./Bot/.env
    command: node /app/Bot/bot.js # Команда для запуска бота
    depends_on:
      - server
    restart: always

  datafrontend:
    image: nginx:latest
    container_name: datafrontend
    ports:
      - "4000:80"
    volumes:
      - ./DataFrontend:/usr/share/nginx/html
    restart: always
    
  frontend:
    image: nginx:latest
    container_name: frontend
    ports:
      - "5000:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    restart: always
